#!/usr/bin/env python3
"""Push this repo's source files to GitHub via the Contents API.

Usage: python3 scripts/push_to_github.py [repo-name]
Default repo: national-park-passport (created beforehand via gh.py).

Uses the stored custom.github credential (surrogate injection, never exposed).
dist/ and __pycache__ are excluded — dist/ is generated by build.py.
"""
import base64
import concurrent.futures
import json
import os
import sys
import urllib.error
import urllib.request

sys.path.insert(0, "/opt/hatch/skills/skill-creator/bin")
from dynamic_credentials import add_surrogate_to_request, read_json_response  # noqa: E402

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
REPO = sys.argv[1] if len(sys.argv) > 1 else "national-park-passport"
EXCLUDE_DIRS = {"dist", "__pycache__", ".git", "node_modules"}
EXCLUDE_FILES = {".DS_Store"}


def api(method, path, body=None):
    url = "https://api.github.com" + path
    data = json.dumps(body).encode() if body is not None else None
    req = urllib.request.Request(url, data=data, method=method)
    req.add_header("Accept", "application/vnd.github+json")
    req.add_header("X-GitHub-Api-Version", "2022-11-28")
    req.add_header("User-Agent", "muse-github-skill")
    if data:
        req.add_header("Content-Type", "application/json")
    add_surrogate_to_request(req, "custom.github", allowed_hosts=("api.github.com",))
    with urllib.request.urlopen(req, timeout=60) as resp:
        return read_json_response(resp)


def collect_files():
    out = []
    for dirpath, dirnames, filenames in os.walk(ROOT):
        dirnames[:] = [d for d in dirnames if d not in EXCLUDE_DIRS]
        for f in sorted(filenames):
            if f in EXCLUDE_FILES or f.endswith(".pyc"):
                continue
            full = os.path.join(dirpath, f)
            rel = os.path.relpath(full, ROOT)
            out.append((rel, full))
    return out


def push_one(owner, repo, rel, full, message):
    with open(full, "rb") as fh:
        content = base64.b64encode(fh.read()).decode()
    sha = None
    try:
        cur = api("GET", f"/repos/{owner}/{repo}/contents/{rel}")
        sha = cur.get("sha")
    except urllib.error.HTTPError as e:
        if e.code != 404:
            raise
    # skip if content identical
    if sha and cur.get("content"):
        existing = cur["content"].replace("\n", "")
        if existing == content:
            return f"skip (unchanged) {rel}"
    body = {"message": message, "content": content}
    if sha:
        body["sha"] = sha
    api("PUT", f"/repos/{owner}/{repo}/contents/{rel}", body)
    return f"pushed {rel}"


def main():
    owner = api("GET", "/user")["login"]
    try:
        api("GET", f"/repos/{owner}/{REPO}")
        print(f"repo {owner}/{REPO} exists, syncing files")
    except urllib.error.HTTPError as e:
        if e.code == 404:
            api("POST", "/user/repos", {
                "name": REPO, "private": False,
                "description": "Gamified national park passport & checklist tool",
            })
            print(f"created repo {owner}/{REPO}")
        else:
            raise

    files = collect_files()
    print(f"pushing {len(files)} files to {owner}/{REPO} ...")
    message = "National Park Passport MVP: static generator + 73 pages + deploy scripts"
    results = []
    with concurrent.futures.ThreadPoolExecutor(max_workers=4) as ex:
        futs = {ex.submit(push_one, owner, REPO, rel, full, message): rel for rel, full in files}
        for fut in concurrent.futures.as_completed(futs):
            try:
                results.append(fut.result())
            except Exception as e:  # noqa: BLE001
                results.append(f"ERROR {futs[fut]}: {e}")
    for r in sorted(results):
        print(" ", r)
    errs = [r for r in results if r.startswith("ERROR")]
    if errs:
        print(f"{len(errs)} errors")
        sys.exit(1)
    print(f"done: https://github.com/{owner}/{REPO}")


if __name__ == "__main__":
    main()
